#
# Linkerd lifecycle test configuration
#
# slow_cooker ->(HTTP/1.1)->
#   bb-p2p ->(gRPC)->
#     bb-broadcast ->(gRPC)->
#       bb-terminus1
#       bb-terminus2
#       ...
#       bb-terminus10
#
---
#
# slow_cooker
#
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: slow-cooker
  name: slow-cooker
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: slow-cooker
    spec:
      containers:
      - image: buoyantio/slow_cooker:1.2.0
        name: slow-cooker
        env:
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: http_proxy
          value: $(HOST_IP):4140
        - name: LIFECYCLE_NS
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        command:
        - "/bin/sh"
        args:
        - "-c"
        - |
          sleep 30 # wait for pods to start
          slow_cooker \
            -qps 1 \
            -concurrency 1 \
            -interval 10s \
            -metric-addr 0.0.0.0:9990 \
            http://bb-p2p.$LIFECYCLE_NS
        ports:
        - name: slow-cooker
          containerPort: 9990
---
#
# bb point-to-point
#
kind: Service
apiVersion: v1
metadata:
  name: bb-p2p
spec:
  selector:
    app: bb-p2p
  ports:
  - name: http
    port: 7070
    targetPort: 7070
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: bb-p2p
  name: bb-p2p
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: bb-p2p
    spec:
      containers:
      - image: buoyantio/bb:v0.0.5
        name: bb-p2p
        env:
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: LIFECYCLE_NS
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        command:
        - "/bin/bash"
        args:
        - "-c"
        - |
          exec \
          /out/bb point-to-point-channel \
          --downstream-timeout 60s \
          --log-level debug \
          --h1-server-port=7070 \
          --grpc-downstream-server=bb-broadcast.$LIFECYCLE_NS \
          --grpc-proxy=$HOST_IP:4340
        ports:
        - containerPort: 7070
          name: http
---
#
# bb broadcast
#
kind: Service
apiVersion: v1
metadata:
  name: bb-broadcast
spec:
  selector:
    app: bb-broadcast
  ports:
  - name: grpc
    port: 8080
    targetPort: 8080
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: bb-broadcast
  name: bb-broadcast
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: bb-broadcast
    spec:
      containers:
      - image: buoyantio/bb:v0.0.5
        name: bb-broadcast
        env:
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: LIFECYCLE_NS
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        command:
        - "/bin/bash"
        args:
        - "-c"
        - |
          exec \
          /out/bb broadcast-channel \
          --downstream-timeout 60s \
          --log-level debug \
          --grpc-server-port=8080 \
          --grpc-downstream-server=bb-terminus1.$LIFECYCLE_NS \
          --grpc-downstream-server=bb-terminus2.$LIFECYCLE_NS \
          --grpc-downstream-server=bb-terminus3.$LIFECYCLE_NS \
          --grpc-downstream-server=bb-terminus4.$LIFECYCLE_NS \
          --grpc-downstream-server=bb-terminus5.$LIFECYCLE_NS \
          --grpc-downstream-server=bb-terminus6.$LIFECYCLE_NS \
          --grpc-downstream-server=bb-terminus7.$LIFECYCLE_NS \
          --grpc-downstream-server=bb-terminus8.$LIFECYCLE_NS \
          --grpc-downstream-server=bb-terminus9.$LIFECYCLE_NS \
          --grpc-downstream-server=bb-terminus10.$LIFECYCLE_NS \
          --grpc-proxy=$HOST_IP:4340
        ports:
        - containerPort: 8080
          name: grpc
---
#
# bb terminus
#
kind: Service
apiVersion: v1
metadata:
  name: bb-terminus1
spec:
  selector:
    app: bb-terminus
  ports:
  - name: grpc
    port: 9090
    targetPort: 9090
---
kind: Service
apiVersion: v1
metadata:
  name: bb-terminus2
spec:
  selector:
    app: bb-terminus
  ports:
  - name: grpc
    port: 9090
    targetPort: 9090
---
kind: Service
apiVersion: v1
metadata:
  name: bb-terminus3
spec:
  selector:
    app: bb-terminus
  ports:
  - name: grpc
    port: 9090
    targetPort: 9090
---
kind: Service
apiVersion: v1
metadata:
  name: bb-terminus4
spec:
  selector:
    app: bb-terminus
  ports:
  - name: grpc
    port: 9090
    targetPort: 9090
---
kind: Service
apiVersion: v1
metadata:
  name: bb-terminus5
spec:
  selector:
    app: bb-terminus
  ports:
  - name: grpc
    port: 9090
    targetPort: 9090
---
kind: Service
apiVersion: v1
metadata:
  name: bb-terminus6
spec:
  selector:
    app: bb-terminus
  ports:
  - name: grpc
    port: 9090
    targetPort: 9090
---
kind: Service
apiVersion: v1
metadata:
  name: bb-terminus7
spec:
  selector:
    app: bb-terminus
  ports:
  - name: grpc
    port: 9090
    targetPort: 9090
---
kind: Service
apiVersion: v1
metadata:
  name: bb-terminus8
spec:
  selector:
    app: bb-terminus
  ports:
  - name: grpc
    port: 9090
    targetPort: 9090
---
kind: Service
apiVersion: v1
metadata:
  name: bb-terminus9
spec:
  selector:
    app: bb-terminus
  ports:
  - name: grpc
    port: 9090
    targetPort: 9090
---
kind: Service
apiVersion: v1
metadata:
  name: bb-terminus10
spec:
  selector:
    app: bb-terminus
  ports:
  - name: grpc
    port: 9090
    targetPort: 9090
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: bb-terminus
  name: bb-terminus
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: bb-terminus
    spec:
      containers:
      - image: buoyantio/bb:v0.0.5
        name: bb-terminus
        command:
        - "/bin/bash"
        args:
        - "-c"
        - |
          exec \
          /out/bb terminus \
          --downstream-timeout 60s \
          --log-level debug \
          --grpc-server-port=9090 \
          --response-text=BANANA0
        ports:
        - containerPort: 9090
          name: grpc
---
#
# Redeploy via kubectl
#
kind: ServiceAccount
apiVersion: v1
metadata:
  name: redeployer
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: lifecycle:redeployer
rules:
- apiGroups: ["extensions"]
  resources: ["deployments"]
  verbs: ["get", "patch"]
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["create", "delete", "get", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: lifecycle:redeployer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: lifecycle:redeployer
subjects:
- kind: ServiceAccount
  name: redeployer
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redeployer
data:
  redeployer: |-
    #!/bin/sh

    # give deployment time to fully roll out
    sleep 60

    LAST=$(date +%s)

    while true; do
      PODS=$(kubectl -n $LIFECYCLE_NS get po --field-selector=status.phase=Running --selector=app=bb-terminus -o jsonpath='{.items[*].metadata.name}')

      SPACES=$(echo "${PODS}" | awk -F" " '{print NF-1}')
      POD_COUNT=$(($SPACES+1))
      echo "found ${POD_COUNT} running pods"

      # restart each pod every minute
      SLEEP_TIME=$(( 60 / $POD_COUNT ))
      if [ $SLEEP_TIME = 0 ]; then
        SLEEP_TIME=1
      fi

      for POD in ${PODS}; do
        kubectl -n $LIFECYCLE_NS delete po $POD

        # bounce services every 30 seconds
        NOW=$(date +%s)
        if [ $(( NOW - LAST )) -gt 30 ]; then
          echo "bouncing services..."
          for i in `seq 1 10`; do
            SVC=$(kubectl -n $LIFECYCLE_NS get svc/bb-terminus$i -o json)
            kubectl -n $LIFECYCLE_NS delete svc/bb-terminus$i
            echo $SVC | kubectl -n $LIFECYCLE_NS apply -f -
          done
          LAST=NOW
        fi

        echo "sleeping for ${SLEEP_TIME} seconds..."
        sleep $SLEEP_TIME
      done

      # redeploy the whole bb-terminus deployment
      echo "redeploying bb-terminus deployment"
      DEPLOY=$(kubectl -n $LIFECYCLE_NS get deploy/bb-terminus -o json)
      echo $DEPLOY | sed -E 's/BANANA[0-9]+/BANANA'$(date +'%s')'/g' | kubectl -n $LIFECYCLE_NS apply -f -

      # give the new deployment time to roll out, before we start deleting pods again
      echo "sleeping for 60 seconds..."
      sleep 60
    done
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: redeployer
  name: redeployer
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redeployer
    spec:
      serviceAccount: redeployer
      containers:
      - image: lachlanevenson/k8s-kubectl:v1.14.0
        name: redeployer
        command:
        - "/data/redeployer"
        env:
        - name: LIFECYCLE_NS
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        volumeMounts:
        - name: redeployer
          mountPath: /data
      volumes:
      - name: redeployer
        configMap:
          name: redeployer
          defaultMode: 0744
