apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-deploy
  namespace: emojivoto
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: emojivoto
    # server: {{ .Values.spec.destination.server }}
    server: https://kubernetes.default.svc
  project: demo
  source:
    path: test-deploy
    repoURL: https://github.com/kmpartner/argo-demo.git
    targetRevision: HEAD